# This is a basic workflow to help you get started with Actions

name: UPDATE

# Controls when the action will run. 
on:
#   schedule:
#     - cron: '1 2,4,6 * * *'
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          presist-credentials: false
          fetch-depth: 0
      - name: set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name : update tiku and commit
        run: |
          rm -rf ./*.json
          python ./main.py
      - name: auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto commit
          commit_username: ${{ secrets.NAME }}
          commit_email: ${{ secrets.EMAIL }}
#       - name: git config
#         run: |
#           git config --local user.email ${{ secrets.EMAIL }}
#           git config --local user.name ${{ secrets.NAME }}
#           git config --list          
#       - name : git commit
#         run: |
#           git add -A
#           git commit -m "test"

      - name: push update
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
